# Generated by Django 5.1 on 2024-11-06 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="posts",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="posts",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="posts_app.posttag",
            ),
        ),
    ]
