# Generated by Django 5.1 on 2024-11-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0002_rename_create_at_comments_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="temp_profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
