# Generated by Django 5.1 on 2024-11-06 14:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0003_profile_temp_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="posts",
            name="description",
            field=ckeditor.fields.RichTextField(default=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default="Sem descrição"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="favorite_song",
            field=models.CharField(blank=True, default="Sem descrição", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="temp_profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="temp_profile_pics/"
            ),
        ),
    ]
