# Generated by Django 5.1.2 on 2024-10-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0003_posts_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=50)),
                ("tag_description", models.CharField(max_length=255)),
            ],
        ),
    ]
