# Generated by Django 5.1 on 2024-11-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "posts_app",
            "0004_remove_profile_created_at_remove_profile_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="posttag",
            name="tag_icon",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
