# Generated by Django 5.1.2 on 2024-10-29 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0004_posttag"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="tag",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts_app.posttag",
            ),
        ),
    ]
