# Generated by Django 5.1 on 2024-11-10 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0014_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
