# Generated by Django 5.1 on 2024-11-10 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0015_delete_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posttag",
            name="tag_icon",
        ),
    ]
